#!/bin/bash

echo "TODOアプリの使用例:"
echo ""
echo "1. タスクを追加:"
echo "   選択: 1"
echo "   入力: 'プロジェクトの資料を作成'"
echo ""
echo "2. タスク一覧を表示:"
echo "   選択: 2"
echo ""
echo "3. タスクを完了:"
echo "   選択: 3"
echo "   タスクID: 1"
echo ""
echo "4. タスクを削除:"
echo "   選択: 4"
echo "   タスクID: 2"
echo ""
echo "5. 終了:"
echo "   選択: 6"
echo ""
echo "実際に使用するには、ターミナルで以下を実行してください:"
echo "python3 todo_app.py"